name: "Daily GitHub Commit"

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC every day

  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update activity log
        run: |
          echo "Automated commit on $(date)" >> activity.log

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add activity.log
          git commit -m "Automated commit on $(date)"
          git push
